{% set version = "3.1.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cartography
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cartography_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cartography/cartography_{{ version }}.tar.gz
  sha256: 987b9352eb0a24160a4a6080cbfaf17fd89df2f83d4470087486d40e5dd07cda

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-classint
    - r-curl
    - r-png
    - r-raster
    - r-sf
    - r-sp
  run:
    - r-base
    - r-rcpp
    - r-classint
    - r-curl
    - r-png
    - r-raster
    - r-sf
    - r-sp

test:
  commands:
    - $R -e "library('cartography')"           # [not win]
    - "\"%R%\" -e \"library('cartography')\""  # [win]

about:
  home: https://github.com/riatelab/cartography/
  license: GPL-3.0-only
  summary: Create and integrate maps in your R workflow. This package helps to design cartographic representations such as proportional symbols, choropleth, typology, flows or discontinuities maps. It also offers several features that improve the graphic presentation of maps, for instance, map palettes, layout elements (scale,
    north arrow, title...), labels or legends. See Giraud and Lambert (2017) <doi:10.1007/978-3-319-57336-6_13>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: cartography
# Title: Thematic Cartography
# Version: 2.3.0
# Authors@R: c( person("Timothee", "Giraud", email = "timothee.giraud@cnrs.fr", role = c("cre","aut"), comment = c(ORCID = "0000-0002-1932-3323")), person("Nicolas", "Lambert", email = "nicolas.lambert@cnrs.fr", role = "aut"), person("Ian", "Fellows", role = "cph", comment = "no overlap algorithm for labels, from wordcloud package"))
# Description: Create and integrate maps in your R workflow. This package helps to design cartographic representations such as proportional symbols, choropleth, typology, flows or discontinuities maps. It also offers several features that improve the graphic presentation of maps, for instance, map palettes, layout elements (scale, north arrow, title...), labels or legends. See Giraud and Lambert (2017) <doi:10.1007/978-3-319-57336-6_13>.
# License: GPL-3
# URL: https://github.com/riatelab/cartography/
# BugReports: https://github.com/riatelab/cartography/issues/
# LazyData: true
# Depends: R (>= 3.3.0)
# Imports: classInt, curl, graphics, methods, png, raster, Rcpp, rgeos, sf (>= 0.6-4), slippymath, sp (>= 1.2-4), stats
# Suggests: SpatialPosition, knitr, rmarkdown, rgdal, tinytest
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# SystemRequirements: GDAL (>= 2.0.1), GEOS (>= 3.4.0), PROJ.4 (>= 4.8.0)
# Encoding: UTF-8
# RoxygenNote: 7.0.2
# NeedsCompilation: yes
# Packaged: 2020-01-27 15:21:15 UTC; tim
# Author: Timothee Giraud [cre, aut] (<https://orcid.org/0000-0002-1932-3323>), Nicolas Lambert [aut], Ian Fellows [cph] (no overlap algorithm for labels, from wordcloud package)
# Maintainer: Timothee Giraud <timothee.giraud@cnrs.fr>
# Repository: CRAN
# Date/Publication: 2020-01-28 09:40:16 UTC
