{% set version = "3.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cartography
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cartography_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cartography/cartography_{{ version }}.tar.gz
  sha256: cf8bf918154b5a07f9d43e18aeeaa01beb1f775185e1e87ad91a3c054cc036be

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-classint
    - r-curl
    - r-png
    - r-raster
    - r-rgeos
    - r-sf >=0.6_4
    - r-slippymath
    - r-sp >=1.2_4
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-classint
    - r-curl
    - r-png
    - r-raster
    - r-rgeos
    - r-sf >=0.6_4
    - r-slippymath
    - r-sp >=1.2_4

test:
  commands:
    - $R -e "library('cartography')"           # [not win]
    - "\"%R%\" -e \"library('cartography')\""  # [win]

about:
  home: https://github.com/riatelab/cartography/
  license: GPL-3.0-only
  summary: Create and integrate maps in your R workflow. This package helps to design cartographic representations such as proportional symbols, choropleth, typology, flows or discontinuities maps. It also offers several features that improve the graphic presentation of maps, for instance, map palettes, layout elements (scale,
    north arrow, title...), labels or legends. See Giraud and Lambert (2017) <doi:10.1007/978-3-319-57336-6_13>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: cartography
# Title: Thematic Cartography
# Version: 2.3.0
# Authors@R: c( person("Timothee", "Giraud", email = "timothee.giraud@cnrs.fr", role = c("cre","aut"), comment = c(ORCID = "0000-0002-1932-3323")), person("Nicolas", "Lambert", email = "nicolas.lambert@cnrs.fr", role = "aut"), person("Ian", "Fellows", role = "cph", comment = "no overlap algorithm for labels, from wordcloud package"))
# Description: Create and integrate maps in your R workflow. This package helps to design cartographic representations such as proportional symbols, choropleth, typology, flows or discontinuities maps. It also offers several features that improve the graphic presentation of maps, for instance, map palettes, layout elements (scale, north arrow, title...), labels or legends. See Giraud and Lambert (2017) <doi:10.1007/978-3-319-57336-6_13>.
# License: GPL-3
# URL: https://github.com/riatelab/cartography/
# BugReports: https://github.com/riatelab/cartography/issues/
# LazyData: true
# Depends: R (>= 3.3.0)
# Imports: classInt, curl, graphics, methods, png, raster, Rcpp, rgeos, sf (>= 0.6-4), slippymath, sp (>= 1.2-4), stats
# Suggests: SpatialPosition, knitr, rmarkdown, rgdal, tinytest
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# SystemRequirements: GDAL (>= 2.0.1), GEOS (>= 3.4.0), PROJ.4 (>= 4.8.0)
# Encoding: UTF-8
# RoxygenNote: 7.0.2
# NeedsCompilation: yes
# Packaged: 2020-01-27 15:21:15 UTC; tim
# Author: Timothee Giraud [cre, aut] (<https://orcid.org/0000-0002-1932-3323>), Nicolas Lambert [aut], Ian Fellows [cph] (no overlap algorithm for labels, from wordcloud package)
# Maintainer: Timothee Giraud <timothee.giraud@cnrs.fr>
# Repository: CRAN
# Date/Publication: 2020-01-28 09:40:16 UTC
